CUDA_VISIBLE_DEVICES=2 python scripts/train.py \
--dataset_type=animalfaces_encode \
--psp_checkpoint_path=/data2/mhf/DXL/Lingxiao/Codes/Paint-by-Example-test/models/Paint-by-Example/animal_faces/2024-09-11T11-30-12_v1/checkpoints/epoch=000037.ckpt \
--exp_dir=/data2/mhf/DXL/Lingxiao/Codes/hyperediting/exp_out/hyper_styleGANinversion_animalfaces_512_5_30_init_v3 \
--learning_rate=0.0001 \
--step_size=5000 \
--gamma=0.3 \
--train_all \
--feature_size=512 \
--transformer_layers=30 \
--c=0.1 \
--workers=128 \
--batch_size=256 \
--test_batch_size=256 \
--test_workers=128 \
--val_interval=800000 \
--save_interval=1000 \
--max_steps=30000 \
--encoder_type=CLIPImageEmbedder \
--optim_name=adam \
--hyperbolic=True \
--hyperbolic_lambda=0.3 \
--reverse_lambda=5 \
--ngpus-per-node 1 \
--dist-url 'tcp://localhost:10029' \
--multiprocessing-distributed \
--dist-backend nccl \
--world-size 1 \
--rank 0
