model:
  base_learning_rate: 1.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    parameterization: "eps"
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "jpg"
    cond_stage_key: "ref"
    image_size: 64
    channels: 4
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_checkpoint: True
        use_fp16: False
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          #attn_type: "vanilla-xformers"
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.HyperbolicCLIPImageEmbedder
      params:
         opts:
            encoder_version: /data2/mhf/DXL/Lingxiao/Cache/huggingface/hub/models--openai--clip-vit-large-patch14
            encoder_type: CLIPImageEmbedder
            feature_size: 512
            transformer_layers: 30
            dataset_type: animalfaces_encode
            hyperbolic: true
            sample_mode: False
            checkpoint_path: /data2/mhf/DXL/Lingxiao/Codes/hyperediting/exp_out/hyper_animalfaces_512_5_30_init_v1/checkpoints/iteration_29000.pt
            psp_checkpoint_path: /data2/mhf/DXL/Lingxiao/Codes/Paint-by-Example-test/models/Paint-by-Example/animal_faces/2024-09-11T11-30-12_v1/checkpoints/epoch=000037.ckpt


data:
  target: main.DataModuleFromConfig
  params:
      batch_size: 24
      wrap: False
      train:
          target: ldm.data.reconstruction.ImagesDataset
          params:
              dataset_type: animalfaces_encode
      validation:
          target: ldm.data.reconstruction.ImagesDataset
          params:
              dataset_type: animalfaces_encode
      test:
          target: ldm.data.reconstruction.ImagesDataset
          params:
              dataset_type: animalfaces_encode

lightning:
  trainer:
    max_epochs: 40
    num_nodes: 1
    accelerator: 'gpu'
    gpus: "1,2"