dataset_paths = {
    'celeba_train': '',
    'celeba_test': '/local/rcs/ll3504/datasets/CelebAMask-HQ/CelebA-HQ-img',
    'celeba_train_sketch': '',
    'celeba_test_sketch': '',
    'celeba_train_segmentation': '',
    'celeba_test_segmentation': '',
    'ffhq': '/data2/mhf/DXL/Lingxiao/datasets/FFHQ',
    'nabirds': '/data2/mhf/DXL/Lingxiao/datasets/nabirds/images',
    'flowers_train': '/data2/mhf/DXL/Lingxiao/datasets/flowers/dataset/train',
    'flowers_train_eva': '/home/zhangyuanyuan/Lingxiao/datasets/flowers_eva/train',
    'flowers_valid': '/data2/mhf/DXL/Lingxiao/datasets/flowers/dataset/valid',
    'flowers_test': '/data2/mhf/DXL/Lingxiao/datasets/flowers/dataset/test',
    'flowers_test_eva': '/home/zhangyuanyuan/Lingxiao/datasets/flowers_eva/test',
    'animal_faces': '/data2/mhf/DXL/Lingxiao/datasets/animals',
    'animal_faces_train_eva': '/home/zhangyuanyuan/Lingxiao/datasets/animals_eva/train',
    'animal_faces_test_eva': '/home/zhangyuanyuan/Lingxiao/datasets/animals_eva/test',
    'animal_faces_10': '/home/zhangyuanyuan/Lingxiao/datasets/animal_faces_10_classes',
    'vgg_faces_train': '/data2/mhf/DXL/Lingxiao/datasets/vggfaces',
    'vgg_faces_test': '/data2/mhf/DXL/Lingxiao/datasets/vggfaces',
    'vgg_faces_train_eva': '/home/zhangyuanyuan/Lingxiao/datasets/vggfaces_eva/train',
    'vgg_faces_test_eva': '/home/zhangyuanyuan/Lingxiao/datasets/vggfaces_eva/test',
}

model_paths = {
    'stylegan_ffhq': 'pretrained_models/stylegan2-ffhq-config-f.pt',
    'stylegan_flowers': 'pretrained_models/stylegan2-flowers.pt',
    'stylegan_animalfaces': 'pretrained_models/stylegan2-animalfaces.pt',
    'stylegan_vggfaces': 'pretrained_models/psp_vggfaces.pt',
    'ir_se50': 'pretrained_models/model_ir_se50.pth',
    'circular_face': 'pretrained_models/CurricularFace_Backbone.pth',
    'mtcnn_pnet': 'pretrained_models/mtcnn/pnet.npy',
    'mtcnn_rnet': 'pretrained_models/mtcnn/rnet.npy',
    'mtcnn_onet': 'pretrained_models/mtcnn/onet.npy',
    'shape_predictor': 'shape_predictor_68_face_landmarks.dat',
    'moco': 'pretrained_models/moco_v2_800ep_pretrain.pth.tar'
}
